rust: 1.88.0 -> 1.89.0; closes #147

diff --git a/rust/Pkgfile b/rust/Pkgfile
--- a/rust/Pkgfile
+++ b/rust/Pkgfile
@@ -6,193 +6,176 @@
 # Optional: libgit2 polly
 
 name=rust
-version=1.88.0
-_date=2025-05-15
-_rustc=1.87.0
+version=1.89.0
+_date=2025-06-26
+_rustc=1.88.0
 _cargo=$_rustc
 release=1
 
 source=(https://static.rust-lang.org/dist/${name}c-$version-src.tar.xz
-	https://static.rust-lang.org/dist/$_date/rust-std-$_rustc-aarch64-unknown-linux-gnu.tar.xz
-	https://static.rust-lang.org/dist/$_date/rustc-$_rustc-aarch64-unknown-linux-gnu.tar.xz
-	https://static.rust-lang.org/dist/$_date/cargo-$_cargo-aarch64-unknown-linux-gnu.tar.xz
-	0001-bootstrap-Change-libexec-dir.patch
-	0002-bootstrap-Change-bash-completion-dir.patch
+    https://static.rust-lang.org/dist/$_date/rust-std-$_rustc-aarch64-unknown-linux-gnu.tar.xz
+    https://static.rust-lang.org/dist/$_date/rustc-$_rustc-aarch64-unknown-linux-gnu.tar.xz
+    https://static.rust-lang.org/dist/$_date/cargo-$_cargo-aarch64-unknown-linux-gnu.tar.xz
+    0001-bootstrap-Change-libexec-dir.patch
+    0002-bootstrap-Change-bash-completion-dir.patch
     0003-bootstrap-Use-lld-mode-only-for-host-linked-targets.patch)
 
 unpack_source() {
-	for file in ${source[@]}; do
-		case ${file##*/} in
-			rustc-${version}-src.tar.xz)
-				echo "Unpacking $(get_filename $file)";
-				bsdtar -p -o -C ${SRC} -xf $(get_filename $file) ;;
-			*.tar.xz)
-				echo "Copying $(get_filename $file)";
-				mkdir -p ${SRC}/${name}c-$version-src/build/cache/${_date} || true
-				cp $(get_filename $file) ${SRC}/${name}c-$version-src/build/cache/${_date} ;;
-			*)
-				cp $(get_filename $file) ${SRC} ;;
-		esac
-	done
+    for file in ${source[@]}; do
+        case ${file##*/} in
+            rustc-${version}-src.tar.xz)
+                echo "Unpacking $(get_filename $file)";
+                bsdtar -p -o -C ${SRC} -xf $(get_filename $file) ;;
+            *.tar.xz)
+                echo "Copying $(get_filename $file)";
+                mkdir -p ${SRC}/${name}c-$version-src/build/cache/${_date} || true
+                cp $(get_filename $file) ${SRC}/${name}c-$version-src/build/cache/${_date} ;;
+            *)
+                cp $(get_filename $file) ${SRC} ;;
+        esac
+    done
 }
 
 _check_version() {
-	local ERROR
-	local DATE="$(awk -F'=' '/^compiler_date=/ {print $2}' $SRC/${name}c-$version-src/src/stage0)"
-	local RUSTC="$(awk -F'=' '/^compiler_version=/ {print $2}' $SRC/${name}c-$version-src/src/stage0)"
+    local ERROR
+    local DATE="$(awk -F'=' '/^compiler_date=/ {print $2}' $SRC/${name}c-$version-src/src/stage0)"
+    local RUSTC="$(awk -F'=' '/^compiler_version=/ {print $2}' $SRC/${name}c-$version-src/src/stage0)"
 
-	printf '\033[0;32m%s\033[0m\n' "Checking versions for bootstrap compiler.."
-	printf '\033[0;32m%s\033[0m\n' "Got _date = $_date && _rustc = $_rustc"
+    printf '\033[0;32m%s\033[0m\n' "Checking versions for bootstrap compiler.."
+    printf '\033[0;32m%s\033[0m\n' "Got _date = $_date && _rustc = $_rustc"
 
-	if [ "$DATE" != "$_date" ]; then
-		printf '\e[1;31m%-6s\e[m\n' "Error: _date $_date != $DATE"
-		ERROR=1
-	fi
-	if [ "$RUSTC" != "$_rustc" ]; then
-		printf '\e[1;31m%-6s\e[m\n' "Error: _rustc $_rustc != $RUSTC"
-		ERROR=1
-	fi
+    if [ "$DATE" != "$_date" ]; then
+        printf '\e[1;31m%-6s\e[m\n' "Error: _date $_date != $DATE"
+        ERROR=1
+    fi
+    if [ "$RUSTC" != "$_rustc" ]; then
+        printf '\e[1;31m%-6s\e[m\n' "Error: _rustc $_rustc != $RUSTC"
+        ERROR=1
+    fi
 
-	[ $ERROR ] && exit 1
-	printf '\033[0;32m%s\033[0m\n' "Versions check out! Proceeding.."
-	unset DATE RUSTC ERROR
+    [ $ERROR ] && exit 1
+    printf '\033[0;32m%s\033[0m\n' "Versions check out! Proceeding.."
+    unset DATE RUSTC ERROR
 }
 
 build() {
-	_check_version
+    _check_version
 
-	cd "${name}c-$version-src"
+    cd "${name}c-$version-src"
 
-	patch -p1 -i $SRC/0001-bootstrap-Change-libexec-dir.patch
-	patch -p1 -i $SRC/0002-bootstrap-Change-bash-completion-dir.patch
-	patch -p1 -i $SRC/0003-bootstrap-Use-lld-mode-only-for-host-linked-targets.patch
+    patch -p1 -i $SRC/0001-bootstrap-Change-libexec-dir.patch
+    patch -p1 -i $SRC/0002-bootstrap-Change-bash-completion-dir.patch
+    patch -p1 -i $SRC/0003-bootstrap-Use-lld-mode-only-for-host-linked-targets.patch
 
 cat <<- EOF > $SRC/bootstrap.toml
-	profile = "dist"
-	change-id = 140732
+    profile = "dist"
+    change-id = 140732
 
-	[llvm]
-	ninja = true
-	link-shared = true
-	download-ci-llvm = false
-	@POLLY@
+    [llvm]
+    ninja = true
+    link-shared = true
+    download-ci-llvm = false
+    @POLLY@
 
-	[install]
-	prefix = "/usr"
+    [install]
+    prefix = "/usr"
 
-	[rust]
-	# LLVM crashes when passing an object through ThinLTO twice.  This is triggered
-	# when using rust code in cross-language LTO if libstd was built using ThinLTO.
-	# http://blog.llvm.org/2019/09/closing-gap-cross-language-lto-between.html
-	# https://github.com/rust-lang/rust/issues/54872
-	channel = "stable"
-	codegen-units = 1
-	codegen-units-std = 1
-	debuginfo-level = 1
-	debuginfo-level-std = 2
-	codegen-tests = false
-	debug-assertions = false
-	rpath = false
-	frame-pointers = true
-	deny-warnings = false
-	optimize = true
-	lld = false
-	use-lld = "external"
-	lto = "fat"
+    [rust]
+    # LLVM crashes when passing an object through ThinLTO twice.  This is triggered
+    # when using rust code in cross-language LTO if libstd was built using ThinLTO.
+    # http://blog.llvm.org/2019/09/closing-gap-cross-language-lto-between.html
+    # https://github.com/rust-lang/rust/issues/54872
+    channel = "stable"
+    codegen-units = 1
+    codegen-units-std = 1
+    debuginfo-level = 1
+    debuginfo-level-std = 2
+    codegen-tests = false
+    debug-assertions = false
+    rpath = false
+    frame-pointers = true
+    deny-warnings = false
+    optimize = true
+    lld = false
+    use-lld = "external"
+    lto = "fat"
   # Link the compiler against `jemalloc`, where on Linux and OSX it should
   # override the default allocator for rustc and LLVM.
   jemalloc = true
 
-	[build]
-	target = ["aarch64-unknown-linux-gnu"]
-	description = "CRUX"
-	tools = ["cargo",
-		"clippy",
-		"rustfmt",
-		"analysis",
-		"src",
-		"rust-demangler",
-		"rust-analyzer",
-		"rust-analyzer-proc-macro-srv",
-		"rustdoc"]
-	docs = false
-	extended = true
-	sanitizers = true
-	profiler = true
-	vendor = true
-	locked-deps = true
-	python = "/usr/bin/python3"
-	@CARGO@
-	@RUST@
-	@RUSTFMT@
+    [build]
+    target = ["aarch64-unknown-linux-gnu"]
+    description = "CRUX"
+    tools = ["cargo",
+        "clippy",
+        "rustfmt",
+        "analysis",
+        "src",
+        "rust-demangler",
+        "rust-analyzer",
+        "rust-analyzer-proc-macro-srv",
+        "rustdoc"]
+    docs = false
+    extended = true
+    sanitizers = true
+    profiler = true
+    vendor = true
+    locked-deps = true
+    python = "/usr/bin/python3"
 
-	[target.aarch64-unknown-linux-gnu]
-	cc = "/usr/bin/gcc"
-	cxx = "/usr/bin/g++"
-	ar = "/usr/bin/gcc-ar"
-	ranlib = "/usr/bin/gcc-ranlib"
-	llvm-config = "/usr/bin/llvm-config"
-	llvm-filecheck = "/usr/bin/FileCheck"
+    [target.aarch64-unknown-linux-gnu]
+    cc = "/usr/bin/gcc"
+    cxx = "/usr/bin/g++"
+    ar = "/usr/bin/gcc-ar"
+    ranlib = "/usr/bin/gcc-ranlib"
+    llvm-config = "/usr/bin/llvm-config"
+    llvm-filecheck = "/usr/bin/FileCheck"
 EOF
 
-	if [ -e '/usr/bin/rustc' ]; then
-		if [[ -z "$(/usr/bin/ldd /usr/bin/rustc | egrep '.*libLLVM.*.so => not found')" ]]; then
-			sed	-e 's|@CARGO@|cargo = "/usr/bin/cargo"|' \
-				-e 's|@RUST@|rustc = "/usr/bin/rustc"|' \
-				-e 's|@RUSTFMT@|rustfmt = "/usr/bin/rustfmt"|' \
-				-i $SRC/bootstrap.toml
-		else
-			sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/bootstrap.toml
-			printf "\e[031mShared library missing, not using system rust to bootstrap.\033[0m\n"
-		fi
-	else
-		sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/bootstrap.toml
-	fi
+    prt-get isinst polly && sed -e 's|@POLLY@|polly = true|' -i $SRC/bootstrap.toml || sed -e 's|@POLLY@||' -i $SRC/bootstrap.toml
 
-	prt-get isinst polly && sed -e 's|@POLLY@|polly = true|' -i $SRC/bootstrap.toml || sed -e 's|@POLLY@||' -i $SRC/bootstrap.toml
+    cat $SRC/bootstrap.toml
 
-	cat $SRC/bootstrap.toml
+    mkdir "$PKGMK_SOURCE_DIR/rust" || true
+    export CARGO_HOME="$PKGMK_SOURCE_DIR/rust"
 
-	mkdir "$PKGMK_SOURCE_DIR/rust" || true
-	export CARGO_HOME="$PKGMK_SOURCE_DIR/rust"
+    ## sccache currently leads to errors
+    #if [ -e '/usr/bin/sccache' ]; then
+    #    export RUSTC_WRAPPER='/usr/bin/sccache'
+    #    export SCCACHE_IDLE_TIMEOUT='1500'
+    #fi
 
-	## sccache currently leads to errors
-	#if [ -e '/usr/bin/sccache' ]; then
-	#	export RUSTC_WRAPPER='/usr/bin/sccache'
-	#	export SCCACHE_IDLE_TIMEOUT='1500'
-	#fi
+    #error: field is never read: `id`
+    #   --> src/bootstrap/lib.rs:280:5
+    #   = note: `-D dead-code` implied by `-D warnings`
+    export RUSTFLAGS+=' -A dead_code'
 
-	#error: field is never read: `id`
-	#   --> src/bootstrap/lib.rs:280:5
-	#   = note: `-D dead-code` implied by `-D warnings`
-	export RUSTFLAGS+=' -A dead_code'
+    unset CFLAGS CXXFLAGS
 
-	unset CFLAGS CXXFLAGS
+    { [ ! -e /usr/include/libssh2.h ] ||
+        export LIBSSH2_SYS_USE_PKG_CONFIG=1; }
+    export RUST_BACKTRACE=full
+    /usr/bin/python3 ./x.py build --config="${SRC}"/bootstrap.toml -j ${JOBS-1}
+    DESTDIR=$PKG /usr/bin/python3 ./x.py --config="${SRC}"/bootstrap.toml install
 
-	{ [ ! -e /usr/include/libssh2.h ] ||
-		export LIBSSH2_SYS_USE_PKG_CONFIG=1; }
-	export RUST_BACKTRACE=full
-	/usr/bin/python3 ./x.py build --config="${SRC}"/bootstrap.toml -j ${JOBS-1}
-	DESTDIR=$PKG /usr/bin/python3 ./x.py --config="${SRC}"/bootstrap.toml install
+    prt-get isinst bash-completion || rm -r $PKG/usr/share/bash-completion
+    prt-get isinst zsh || rm -r $PKG/usr/share/zsh
 
-	prt-get isinst bash-completion || rm -r $PKG/usr/share/bash-completion
-	prt-get isinst zsh || rm -r $PKG/usr/share/zsh
+    # cleanup
+    rm -r $PKG/usr/share/doc
+    rm $PKG/usr/lib/rustlib/{components,manifest-rustc,rust-installer-version,uninstall.sh}
 
-	# cleanup
-	rm -r $PKG/usr/share/doc
-	rm $PKG/usr/lib/rustlib/{components,manifest-rustc,rust-installer-version,uninstall.sh}
+    # Remove analysis data for libs that weren't installed
+    local file lib
+    while read -rd '' file; do
+        lib="${file%.json}.rlib"
+        lib="${lib/\/analysis\///lib/}"
+        if [[ ! -e $lib ]]; then
+            echo "missing '$lib'"
+            rm -v "$file"
+        fi
+    done < <(find "$PKG/usr/lib/rustlib"  -path '*/analysis/*.json' -print0)
 
-	# Remove analysis data for libs that weren't installed
-	local file lib
-	while read -rd '' file; do
-		lib="${file%.json}.rlib"
-		lib="${lib/\/analysis\///lib/}"
-		if [[ ! -e $lib ]]; then
-			echo "missing '$lib'"
-			rm -v "$file"
-		fi
-	done < <(find "$PKG/usr/lib/rustlib"  -path '*/analysis/*.json' -print0)
-
-	find $PKG/usr -name "*.old" -delete
-	rm $PKG/usr/lib/rustlib/{install.log,manifest-*}
+    find $PKG/usr -name "*.old" -delete
+    rm $PKG/usr/lib/rustlib/{install.log,manifest-*}
 }
